python -m training_simplified.main \
  --name clipself_coco_test1_eva_vitb16 \
  --model EVA02-CLIP-B-16 \
  --pretrained eva \
  --precision fp32 \
  --cache_dir checkpoints/EVA02_CLIP_B_psz16_s8B.pt \
  --dataset_type grid_distill \
  --train_data data/coco/annotations/instances_train2017.json \
  --train_image_root data/coco/train2017/ \
  --val_data data/coco/annotations/instances_train2017.json \
  --val_image_root data/coco/train2017/ \
  --epochs 6 \
  --batch_size 2 \
  --lr 1e-5 \
  --wd 0.1 \